'use strict';

module.exports = {
    async up(queryInterface, Sequelize) {
        const now = new Date();

        const abilities = [
            {
                name: 'Cleave',
                description: 'Basic strength cleave attack.',
                icon: 'abilities/strenght/cleave.jfif',
                skillId: 1,
                tierId: 1,
                typeId: 1,
                attack: '1d2',
                weight: '50',
                createdAt: now,
                updatedAt: now,
                actionTypeId: 1,
                spellLevel: 0,
                damageTypeId: 1,
                requiresAttackRoll: true,
                requiresSaving_throw: false,
                savingThrowSkillId: null
            },
            {
                name: 'Heavy Strike',
                description: 'Heavy strength strike.',
                icon: 'abilities/strenght/heavyStrike.jfif',
                skillId: 1,
                tierId: 2,
                typeId: 1,
                attack: '1d3',
                weight: '45',
                createdAt: now,
                updatedAt: now,
                actionTypeId: 1,
                spellLevel: 1,
                damageTypeId: 1,
                requiresAttackRoll: true,
                requiresSaving_throw: false,
                savingThrowSkillId: null
            },
            {
                name: 'Sweeping Slash',
                description: 'Wide melee swing that hits multiple nearby enemies.',
                icon: 'abilities/strenght/sweepingSlash.jfif',
                skillId: 1,
                tierId: 3,
                typeId: 1,
                attack: '1d4',
                weight: '30',
                createdAt: now,
                updatedAt: now,
                actionTypeId: 1,
                spellLevel: 2,
                damageTypeId: 1,
                requiresAttackRoll: true,
                requiresSaving_throw: false,
                savingThrowSkillId: null
            },
            {
                name: 'Crushing Blow',
                description: 'A devastating overhead strike that shatters defenses.',
                icon: 'abilities/strenght/crushingBlow.jfif',
                skillId: 1,
                tierId: 5,
                typeId: 1,
                attack: '1d6',
                weight: '14',
                createdAt: now,
                updatedAt: now,
                actionTypeId: 1,
                spellLevel: 4,
                damageTypeId: 1,
                requiresAttackRoll: true,
                requiresSaving_throw: false,
                savingThrowSkillId: null
            },
            {
                name: 'Titanbreaker',
                description: 'Legendary melee finisher for high-level encounters.',
                icon: 'abilities/strenght/titanbreaker.jfif',
                skillId: 1,
                tierId: 7,
                typeId: 1,
                attack: '1d8',
                weight: '4',
                createdAt: now,
                updatedAt: now,
                actionTypeId: 1,
                spellLevel: 6,
                damageTypeId: 1,
                requiresAttackRoll: true,
                requiresSaving_throw: false,
                savingThrowSkillId: null
            },
            {
                name: 'Immolate',
                description: 'Basic fire intelligence spell.',
                icon: 'abilities/inteligence/immolate.jfif',
                skillId: 5,
                tierId: 1,
                typeId: 1,
                attack: '1d2',
                weight: '50',
                createdAt: now,
                updatedAt: now,
                actionTypeId: 1,
                spellLevel: 0,
                damageTypeId: 2,
                requiresAttackRoll: false,
                requiresSaving_throw: true,
                savingThrowSkillId: 8
            },
            {
                name: 'Acid Spray',
                description: 'Acid intelligence attack.',
                icon: 'abilities/inteligence/acidSpray.jfif',
                skillId: 5,
                tierId: 2,
                typeId: 1,
                attack: '1d3',
                weight: '45',
                createdAt: now,
                updatedAt: now,
                actionTypeId: 1,
                spellLevel: 1,
                damageTypeId: 2,
                requiresAttackRoll: false,
                requiresSaving_throw: true,
                savingThrowSkillId: 8
            },
            {
                name: 'Thunderwave',
                description: 'A booming shockwave that crushes nearby targets.',
                icon: 'abilities/inteligence/thunderwave.jfif',
                skillId: 5,
                tierId: 3,
                typeId: 1,
                attack: '1d4',
                weight: '30',
                createdAt: now,
                updatedAt: now,
                actionTypeId: 1,
                spellLevel: 2,
                damageTypeId: 2,
                requiresAttackRoll: false,
                requiresSaving_throw: true,
                savingThrowSkillId: 8
            },
            {
                name: 'Chain Lightning',
                description: 'Arcane lightning that jumps between enemies.',
                icon: 'abilities/inteligence/chainLightning.jfif',
                skillId: 5,
                tierId: 5,
                typeId: 1,
                attack: '1d6',
                weight: '14',
                createdAt: now,
                updatedAt: now,
                actionTypeId: 1,
                spellLevel: 4,
                damageTypeId: 2,
                requiresAttackRoll: false,
                requiresSaving_throw: true,
                savingThrowSkillId: 8
            },
            {
                name: 'Meteor Swarm',
                description: 'Ultimate arcanism devastation for endgame fights.',
                icon: 'abilities/inteligence/meteorSwarm.jfif',
                skillId: 5,
                tierId: 8,
                typeId: 1,
                attack: '1d8',
                weight: '2',
                createdAt: now,
                updatedAt: now,
                actionTypeId: 1,
                spellLevel: 7,
                damageTypeId: 2,
                requiresAttackRoll: false,
                requiresSaving_throw: true,
                savingThrowSkillId: 8
            },
            {
                name: 'Heavy shot',
                description: 'Heavy dexterity ranged attack.',
                icon: 'abilities/dexterity/heavyShot.jfif',
                skillId: 9,
                tierId: 1,
                typeId: 1,
                attack: '1d2',
                weight: '50',
                createdAt: now,
                updatedAt: now,
                actionTypeId: 1,
                spellLevel: 0,
                damageTypeId: 1,
                requiresAttackRoll: true,
                requiresSaving_throw: false,
                savingThrowSkillId: null
            },
            {
                name: 'Explosive shot',
                description: 'Explosive dexterity ranged attack.',
                icon: 'abilities/dexterity/explosiveShot.jfif',
                skillId: 9,
                tierId: 2,
                typeId: 1,
                attack: '1d3',
                weight: '45',
                createdAt: now,
                updatedAt: now,
                actionTypeId: 1,
                spellLevel: 1,
                damageTypeId: 1,
                requiresAttackRoll: true,
                requiresSaving_throw: false,
                savingThrowSkillId: null
            },
            {
                name: 'Piercing Volley',
                description: 'A focused burst of arrows that pierce targets.',
                icon: 'abilities/dexterity/piercingVolley.jfif',
                skillId: 9,
                tierId: 3,
                typeId: 1,
                attack: '1d4',
                weight: '30',
                createdAt: now,
                updatedAt: now,
                actionTypeId: 1,
                spellLevel: 2,
                damageTypeId: 1,
                requiresAttackRoll: true,
                requiresSaving_throw: false,
                savingThrowSkillId: null
            },
            {
                name: 'Sniper Mark',
                description: 'Deadly precision shot with high critical impact.',
                icon: 'abilities/dexterity/sniperMark.jfif',
                skillId: 9,
                tierId: 5,
                typeId: 1,
                attack: '1d6',
                weight: '14',
                createdAt: now,
                updatedAt: now,
                actionTypeId: 1,
                spellLevel: 4,
                damageTypeId: 1,
                requiresAttackRoll: true,
                requiresSaving_throw: false,
                savingThrowSkillId: null
            },
            {
                name: 'Rain of Arrows',
                description: 'Late-game storm of projectiles across the battlefield.',
                icon: 'abilities/dexterity/rainOfArrows.jfif',
                skillId: 9,
                tierId: 7,
                typeId: 1,
                attack: '1d8',
                weight: '4',
                createdAt: now,
                updatedAt: now,
                actionTypeId: 1,
                spellLevel: 6,
                damageTypeId: 1,
                requiresAttackRoll: true,
                requiresSaving_throw: false,
                savingThrowSkillId: null
            },
            {
                name: 'Vicious Mockery',
                description: 'Psychic insult that wounds through humiliation.',
                icon: 'abilities/charisma/viciousMockery.jfif',
                skillId: 13,
                tierId: 1,
                typeId: 1,
                attack: '1d2',
                weight: '45',
                createdAt: now,
                updatedAt: now,
                actionTypeId: 1,
                spellLevel: 0,
                damageTypeId: 9,
                requiresAttackRoll: false,
                requiresSaving_throw: true,
                savingThrowSkillId: 18
            },
            {
                name: 'Dissonant Whispers',
                description: 'Tormenting whispers that tear at the target mind.',
                icon: 'abilities/charisma/dissonantWhispers.jfif',
                skillId: 13,
                tierId: 2,
                typeId: 1,
                attack: '1d3',
                weight: '38',
                createdAt: now,
                updatedAt: now,
                actionTypeId: 1,
                spellLevel: 1,
                damageTypeId: 9,
                requiresAttackRoll: false,
                requiresSaving_throw: true,
                savingThrowSkillId: 18
            },
            {
                name: 'Mind Spike',
                description: 'Focused mental strike that tracks fleeing enemies.',
                icon: 'abilities/charisma/mindSpike.jfif',
                skillId: 13,
                tierId: 3,
                typeId: 1,
                attack: '1d4',
                weight: '26',
                createdAt: now,
                updatedAt: now,
                actionTypeId: 1,
                spellLevel: 2,
                damageTypeId: 9,
                requiresAttackRoll: false,
                requiresSaving_throw: true,
                savingThrowSkillId: 18
            },
            {
                name: 'Synaptic Pulse',
                description: 'Psionic burst that overloads enemy thoughts.',
                icon: 'abilities/charisma/synapticPulse.jfif',
                skillId: 13,
                tierId: 5,
                typeId: 1,
                attack: '1d6',
                weight: '12',
                createdAt: now,
                updatedAt: now,
                actionTypeId: 1,
                spellLevel: 4,
                damageTypeId: 9,
                requiresAttackRoll: false,
                requiresSaving_throw: true,
                savingThrowSkillId: 18
            },
            {
                name: 'Word of Ruin',
                description: 'A catastrophic command that crushes weak minds.',
                icon: 'abilities/charisma/wordOfRuin.jfif',
                skillId: 13,
                tierId: 8,
                typeId: 1,
                attack: '1d8',
                weight: '2',
                createdAt: now,
                updatedAt: now,
                actionTypeId: 1,
                spellLevel: 7,
                damageTypeId: 9,
                requiresAttackRoll: false,
                requiresSaving_throw: true,
                savingThrowSkillId: 18
            },
            {
                name: 'Guiding Bolt',
                description: 'Radiant blast that marks enemies for follow-up attacks.',
                icon: 'abilities/sacred/guidingBolt.jfif',
                skillId: 17,
                tierId: 1,
                typeId: 1,
                attack: '1d2',
                weight: '45',
                createdAt: now,
                updatedAt: now,
                actionTypeId: 1,
                spellLevel: 0,
                damageTypeId: 8,
                requiresAttackRoll: true,
                requiresSaving_throw: false,
                savingThrowSkillId: null
            },
            {
                name: 'Sacred Flame',
                description: 'Holy fire that burns the impure.',
                icon: 'abilities/sacred/sacredFlame.jfif',
                skillId: 17,
                tierId: 2,
                typeId: 1,
                attack: '1d3',
                weight: '38',
                createdAt: now,
                updatedAt: now,
                actionTypeId: 1,
                spellLevel: 1,
                damageTypeId: 8,
                requiresAttackRoll: false,
                requiresSaving_throw: true,
                savingThrowSkillId: 18
            },
            {
                name: 'Spirit Lance',
                description: 'A spear of light hurled at distant enemies.',
                icon: 'abilities/sacred/spiritLance.jfif',
                skillId: 17,
                tierId: 3,
                typeId: 1,
                attack: '1d4',
                weight: '26',
                createdAt: now,
                updatedAt: now,
                actionTypeId: 1,
                spellLevel: 2,
                damageTypeId: 8,
                requiresAttackRoll: false,
                requiresSaving_throw: true,
                savingThrowSkillId: 18
            },
            {
                name: 'Divine Wrath',
                description: 'Calls down sacred judgment on a chosen foe.',
                icon: 'abilities/sacred/divineWrath.jfif',
                skillId: 17,
                tierId: 5,
                typeId: 1,
                attack: '1d6',
                weight: '12',
                createdAt: now,
                updatedAt: now,
                actionTypeId: 1,
                spellLevel: 4,
                damageTypeId: 8,
                requiresAttackRoll: false,
                requiresSaving_throw: true,
                savingThrowSkillId: 18
            },
            {
                name: 'Judgement Nova',
                description: 'Endgame holy detonation against forces of darkness.',
                icon: 'abilities/sacred/judgementNova.jfif',
                skillId: 17,
                tierId: 8,
                typeId: 1,
                attack: '1d8',
                weight: '2',
                createdAt: now,
                updatedAt: now,
                actionTypeId: 1,
                spellLevel: 7,
                damageTypeId: 8,
                requiresAttackRoll: false,
                requiresSaving_throw: true,
                savingThrowSkillId: 18
            },
            {
                name: 'Shadow Bolt',
                description: 'A dark projectile that drains life essence.',
                icon: 'abilities/occultism/shadowBolt.jfif',
                skillId: 21,
                tierId: 1,
                typeId: 1,
                attack: '1d2',
                weight: '45',
                createdAt: now,
                updatedAt: now,
                actionTypeId: 1,
                spellLevel: 0,
                damageTypeId: 7,
                requiresAttackRoll: false,
                requiresSaving_throw: true,
                savingThrowSkillId: 18
            },
            {
                name: 'Necrotic Touch',
                description: 'Corrupting touch that rots flesh and armor.',
                icon: 'abilities/occultism/necroticTouch.jfif',
                skillId: 21,
                tierId: 2,
                typeId: 1,
                attack: '1d3',
                weight: '38',
                createdAt: now,
                updatedAt: now,
                actionTypeId: 1,
                spellLevel: 1,
                damageTypeId: 7,
                requiresAttackRoll: false,
                requiresSaving_throw: true,
                savingThrowSkillId: 18
            },
            {
                name: 'Soul Rend',
                description: 'Tears at the spirit, causing persistent pain.',
                icon: 'abilities/occultism/soulRend.jfif',
                skillId: 21,
                tierId: 3,
                typeId: 1,
                attack: '1d4',
                weight: '26',
                createdAt: now,
                updatedAt: now,
                actionTypeId: 1,
                spellLevel: 2,
                damageTypeId: 7,
                requiresAttackRoll: false,
                requiresSaving_throw: true,
                savingThrowSkillId: 18
            },
            {
                name: 'Blight',
                description: 'Drains vitality with a powerful wave of decay.',
                icon: 'abilities/occultism/blight.jfif',
                skillId: 21,
                tierId: 5,
                typeId: 1,
                attack: '1d6',
                weight: '12',
                createdAt: now,
                updatedAt: now,
                actionTypeId: 1,
                spellLevel: 4,
                damageTypeId: 7,
                requiresAttackRoll: false,
                requiresSaving_throw: true,
                savingThrowSkillId: 18
            },
            {
                name: 'Abyssal Cataclysm',
                description: 'Ultimate dark arts eruption for the highest tiers.',
                icon: 'abilities/occultism/abyssalCataclysm.jfif',
                skillId: 21,
                tierId: 8,
                typeId: 1,
                attack: '1d8',
                weight: '2',
                createdAt: now,
                updatedAt: now,
                actionTypeId: 1,
                spellLevel: 7,
                damageTypeId: 7,
                requiresAttackRoll: false,
                requiresSaving_throw: true,
                savingThrowSkillId: 18
            },
            {
                name: 'Cure Wounds',
                description: 'Basic divine healing touch for early adventures.',
                icon: 'abilities/sacred/cureWounds.jfif',
                skillId: 20,
                tierId: 1,
                typeId: 2,
                attack: '1d2',
                weight: '45',
                createdAt: now,
                updatedAt: now,
                actionTypeId: 1,
                spellLevel: 0,
                damageTypeId: 12,
                requiresAttackRoll: false,
                requiresSaving_throw: false,
                savingThrowSkillId: null
            },
            {
                name: 'Prayer of Healing',
                description: 'Mid-tier group healing prayer.',
                icon: 'abilities/sacred/prayerOfHealing.jfif',
                skillId: 20,
                tierId: 3,
                typeId: 2,
                attack: '1d4',
                weight: '22',
                createdAt: now,
                updatedAt: now,
                actionTypeId: 1,
                spellLevel: 2,
                damageTypeId: 12,
                requiresAttackRoll: false,
                requiresSaving_throw: false,
                savingThrowSkillId: null
            },
            {
                name: 'Mass Heal',
                description: 'High-tier miracle that restores the whole party.',
                icon: 'abilities/sacred/massHeal.jfif',
                skillId: 20,
                tierId: 8,
                typeId: 2,
                attack: '1d8',
                weight: '1',
                createdAt: now,
                updatedAt: now,
                actionTypeId: 1,
                spellLevel: 7,
                damageTypeId: 12,
                requiresAttackRoll: false,
                requiresSaving_throw: false,
                savingThrowSkillId: null
            },
            {
                name: 'Bless',
                description: 'Improves allies accuracy and resolve.',
                icon: 'abilities/sacred/bless.jfif',
                skillId: 17,
                tierId: 1,
                typeId: 3,
                attack: '1d2',
                weight: '40',
                createdAt: now,
                updatedAt: now,
                actionTypeId: 1,
                spellLevel: 0,
                damageTypeId: 10,
                requiresAttackRoll: false,
                requiresSaving_throw: false,
                savingThrowSkillId: null
            },
            {
                name: 'Haste',
                description: 'Greatly increases action speed for one ally.',
                icon: 'abilities/inteligence/haste.jfif',
                skillId: 5,
                tierId: 4,
                typeId: 3,
                attack: '1d5',
                weight: '15',
                createdAt: now,
                updatedAt: now,
                actionTypeId: 1,
                spellLevel: 3,
                damageTypeId: 10,
                requiresAttackRoll: false,
                requiresSaving_throw: false,
                savingThrowSkillId: null
            },
            {
                name: 'Holy Aura',
                description: 'Legendary protective aura for endgame encounters.',
                icon: 'abilities/sacred/holyAura.jfif',
                skillId: 17,
                tierId: 7,
                typeId: 3,
                attack: '1d8',
                weight: '2',
                createdAt: now,
                updatedAt: now,
                actionTypeId: 1,
                spellLevel: 6,
                damageTypeId: 10,
                requiresAttackRoll: false,
                requiresSaving_throw: false,
                savingThrowSkillId: null
            },
            {
                name: 'Bane',
                description: 'Weakens enemy offense and confidence.',
                icon: 'abilities/occultism/bane.jfif',
                skillId: 21,
                tierId: 1,
                typeId: 4,
                attack: '1d2',
                weight: '38',
                createdAt: now,
                updatedAt: now,
                actionTypeId: 1,
                spellLevel: 0,
                damageTypeId: 7,
                requiresAttackRoll: false,
                requiresSaving_throw: true,
                savingThrowSkillId: 18
            },
            {
                name: 'Hold Person',
                description: 'Paralyzes humanoid targets for tactical control.',
                icon: 'abilities/inteligence/holdPerson.jfif',
                skillId: 6,
                tierId: 3,
                typeId: 4,
                attack: '1d4',
                weight: '20',
                createdAt: now,
                updatedAt: now,
                actionTypeId: 1,
                spellLevel: 2,
                damageTypeId: 9,
                requiresAttackRoll: false,
                requiresSaving_throw: true,
                savingThrowSkillId: 18
            },
            {
                name: 'Bestow Curse',
                description: 'High-tier curse that cripples enemy effectiveness.',
                icon: 'abilities/occultism/bestowCurse.jfif',
                skillId: 23,
                tierId: 5,
                typeId: 4,
                attack: '1d6',
                weight: '10',
                createdAt: now,
                updatedAt: now,
                actionTypeId: 1,
                spellLevel: 4,
                damageTypeId: 7,
                requiresAttackRoll: false,
                requiresSaving_throw: true,
                savingThrowSkillId: 18
            },
            {
                name: 'Mage Armor',
                description: 'Arcane shield that boosts defense in early game.',
                icon: 'abilities/inteligence/mageArmor.jfif',
                skillId: 8,
                tierId: 1,
                typeId: 5,
                attack: '1d2',
                weight: '35',
                createdAt: now,
                updatedAt: now,
                actionTypeId: 1,
                spellLevel: 0,
                damageTypeId: 10,
                requiresAttackRoll: false,
                requiresSaving_throw: false,
                savingThrowSkillId: null
            },
            {
                name: 'Misty Step',
                description: 'Short-range teleport for repositioning and escape.',
                icon: 'abilities/dexterity/mistyStep.jfif',
                skillId: 12,
                tierId: 3,
                typeId: 5,
                attack: '1d4',
                weight: '18',
                createdAt: now,
                updatedAt: now,
                actionTypeId: 1,
                spellLevel: 2,
                damageTypeId: 10,
                requiresAttackRoll: false,
                requiresSaving_throw: false,
                savingThrowSkillId: null
            },
            {
                name: 'Greater Invisibility',
                description: 'Endgame stealth utility for decisive tactical advantage.',
                icon: 'abilities/dexterity/greaterInvisibility.jfif',
                skillId: 10,
                tierId: 6,
                typeId: 5,
                attack: '1d7',
                weight: '6',
                createdAt: now,
                updatedAt: now,
                actionTypeId: 1,
                spellLevel: 5,
                damageTypeId: 10,
                requiresAttackRoll: false,
                requiresSaving_throw: false,
                savingThrowSkillId: null
            }
        ];

        await queryInterface.bulkInsert('Abilities', abilities);
    },

    async down(queryInterface, Sequelize) {
        await queryInterface.bulkDelete('Abilities', {
            name: [
                'Cleave',
                'Heavy Strike',
                'Sweeping Slash',
                'Crushing Blow',
                'Titanbreaker',
                'Immolate',
                'Acid Spray',
                'Thunderwave',
                'Chain Lightning',
                'Meteor Swarm',
                'Heavy shot',
                'Explosive shot',
                'Piercing Volley',
                'Sniper Mark',
                'Rain of Arrows',
                'Vicious Mockery',
                'Dissonant Whispers',
                'Mind Spike',
                'Synaptic Pulse',
                'Word of Ruin',
                'Guiding Bolt',
                'Sacred Flame',
                'Spirit Lance',
                'Divine Wrath',
                'Judgement Nova',
                'Shadow Bolt',
                'Necrotic Touch',
                'Soul Rend',
                'Blight',
                'Abyssal Cataclysm',
                'Cure Wounds',
                'Prayer of Healing',
                'Mass Heal',
                'Bless',
                'Haste',
                'Holy Aura',
                'Bane',
                'Hold Person',
                'Bestow Curse',
                'Mage Armor',
                'Misty Step',
                'Greater Invisibility'
            ]
        });
    }
};
