'use strict';

module.exports = {
    async up(queryInterface, Sequelize) {
        const now = new Date();

        await queryInterface.bulkInsert('Classes', [
            {
                id: 1,
                name: 'Peasant',
                description: 'Um camponês simples, sem habilidades especiais.',
                icon: 'icons/classes/peasant.jfif',
                image: 'icons/classes/peasant.jfif',
                color1: 'white',
                color2: 'gray',
                principalAttribute: 1,
                secondaryAttribute: 1,
                createdAt: now,
                updatedAt: now,
            },
            {
                id: 2,
                name: 'Warrior',
                description: 'Um combatente robusto que confia na força bruta.',
                icon: 'icons/classes/warrior.jfif',
                image: 'icons/classes/warrior.jfif',
                color1: 'red',
                color2: 'red',
                principalAttribute: 1,
                secondaryAttribute: 1,
                createdAt: now,
                updatedAt: now,
            },
            {
                id: 3,
                name: 'Spellblade',
                description: 'Um guerreiro que mistura força física com magia.',
                icon: 'icons/classes/spellblade.jfif',
                image: 'icons/classes/spellblade.jfif',
                color1: 'red',
                color2: 'blue',
                principalAttribute: 1,
                secondaryAttribute: 2,
                createdAt: now,
                updatedAt: now,
            },
            {
                id: 4,
                name: 'Swashbuckler',
                description: 'Um duelista ágil e destemido.',
                icon: 'icons/classes/swashbuckler.jfif',
                image: 'icons/classes/swashbuckler.jfif',
                color1: 'red',
                color2: 'green',
                principalAttribute: 1,
                secondaryAttribute: 3,
                createdAt: now,
                updatedAt: now,
            },
            {
                id: 5,
                name: 'Paladin',
                description: 'Um cavaleiro honrado que protege os fracos.',
                icon: 'icons/classes/knight.jfif',
                image: 'icons/classes/knight.jfif',
                color1: 'red',
                color2: 'pink',
                principalAttribute: 1,
                secondaryAttribute: 4,
                createdAt: now,
                updatedAt: now,
            },
            {
                id: 6,
                name: 'Crusader',
                description: 'Um guerreiro sagrado que luta pela justiça.',
                icon: 'icons/classes/paladin.jfif',
                image: 'icons/classes/paladin.jfif',
                color1: 'red',
                color2: 'yellow',
                principalAttribute: 1,
                secondaryAttribute: 5,
                createdAt: now,
                updatedAt: now,
            },
            {
                id: 7,
                name: 'Hexblade',
                description: 'Um guerreiro sombrio que canaliza magia oculta.',
                icon: 'icons/classes/hexblade.jfif',
                image: 'icons/classes/hexblade.jfif',
                color1: 'red',
                color2: 'purple',
                principalAttribute: 1,
                secondaryAttribute: 6,
                createdAt: now,
                updatedAt: now,
            },
            {
                id: 8,
                name: 'Wizard',
                description: 'Um estudioso das artes arcanas.',
                icon: 'icons/classes/wizard.jfif',
                image: 'icons/classes/wizard.jfif',
                color1: 'blue',
                color2: 'blue',
                principalAttribute: 2,
                secondaryAttribute: 2,
                createdAt: now,
                updatedAt: now,
            },
            {
                id: 9,
                name: 'Arcane Archer',
                description: 'Um arqueiro que canaliza magia em seus disparos.',
                icon: 'icons/classes/arcane archer.jfif',
                image: 'icons/classes/arcane archer.jfif',
                color1: 'blue',
                color2: 'green',
                principalAttribute: 2,
                secondaryAttribute: 3,
                createdAt: now,
                updatedAt: now,
            },
            {
                id: 10,
                name: 'Illusionist',
                description: 'Um mago que conjura feitiços através da música.',
                icon: 'icons/classes/spellsinger.jfif',
                image: 'icons/classes/spellsinger.jfif',
                color1: 'blue',
                color2: 'pink',
                principalAttribute: 2,
                secondaryAttribute: 4,
                createdAt: now,
                updatedAt: now,
            },
            {
                id: 11,
                name: 'Theurgist',
                description: 'Um conjurador que canaliza poderes divinos e arcanos.',
                icon: 'icons/classes/theurgist.jfif',
                image: 'icons/classes/theurgist.jfif',
                color1: 'blue',
                color2: 'yellow',
                principalAttribute: 2,
                secondaryAttribute: 5,
                createdAt: now,
                updatedAt: now,
            },
            {
                id: 12,
                name: 'Summoner',
                description: 'Um mestre das ilusões e enganos.',
                icon: 'icons/classes/illusionist.jfif',
                image: 'icons/classes/illusionist.jfif',
                color1: 'blue',
                color2: 'purple',
                principalAttribute: 2,
                secondaryAttribute: 6,
                createdAt: now,
                updatedAt: now,
            },
            {
                id: 13,
                name: 'Ranger',
                description: 'Um caçador que domina a natureza e o arco.',
                icon: 'icons/classes/ranger.jfif',
                image: 'icons/classes/ranger.jfif',
                color1: 'green',
                color2: 'yellow',
                principalAttribute: 3,
                secondaryAttribute: 5,
                createdAt: now,
                updatedAt: now,
            },
            {
                id: 14,
                name: 'Trickster',
                description: 'Um trapaceiro astuto e imprevisível.',
                icon: 'icons/classes/trickster.jfif',
                image: 'icons/classes/trickster.jfif',
                color1: 'green',
                color2: 'pink',
                principalAttribute: 3,
                secondaryAttribute: 4,
                createdAt: now,
                updatedAt: now,
            },
            {
                id: 15,
                name: 'Monk',
                description: 'Um mestre das artes marciais e da disciplina espiritual.',
                icon: 'icons/classes/monk.jfif',
                image: 'icons/classes/monk.jfif',
                color1: 'green',
                color2: 'yellow',
                principalAttribute: 3,
                secondaryAttribute: 5,
                createdAt: now,
                updatedAt: now,
            },
            {
                id: 16,
                name: 'Assassin',
                description: 'Um matador furtivo que age nas sombras.',
                icon: 'icons/classes/assassin.jfif',
                image: 'icons/classes/assassin.jfif',
                color1: 'green',
                color2: 'purple',
                principalAttribute: 3,
                secondaryAttribute: 6,
                createdAt: now,
                updatedAt: now,
            },
            {
                id: 17,
                name: 'Bard',
                description: 'Um artista que inspira aliados com música e magia.',
                icon: 'icons/classes/bard.jfif',
                image: 'icons/classes/bard.jfif',
                color1: 'pink',
                color2: 'pink',
                principalAttribute: 4,
                secondaryAttribute: 4,
                createdAt: now,
                updatedAt: now,
            },
            {
                id: 18,
                name: 'Hierophant',
                description: 'Um líder espiritual que guia com sabedoria.',
                icon: 'icons/classes/hierophant.jfif',
                image: 'icons/classes/hierophant.jfif',
                color1: 'pink',
                color2: 'yellow',
                principalAttribute: 4,
                secondaryAttribute: 5,
                createdAt: now,
                updatedAt: now,
            },
            {
                id: 19,
                name: 'Warlock',
                description: 'Um conjurador que faz pactos sombrios.',
                icon: 'icons/classes/warlock.jfif',
                image: 'icons/classes/warlock.jfif',
                color1: 'pink',
                color2: 'purple',
                principalAttribute: 4,
                secondaryAttribute: 6,
                createdAt: now,
                updatedAt: now,
            },
            {
                id: 20,
                name: 'Cleric',
                description: 'Um sacerdote devoto que canaliza milagres e proteção divina.',
                icon: 'icons/classes/cleric.jfif',
                image: 'icons/classes/cleric.jfif',
                color1: 'yellow', // Sacred
                color2: 'yellow', // Secondary 5 (Sacred)
                principalAttribute: 5,
                secondaryAttribute: 5,
                createdAt: now,
                updatedAt: now,
            },
            {
                id: 21,
                name: 'Demonologist',
                description: 'Um estudioso do abismo que domina pactos e conjurações sombrias.',
                icon: 'icons/classes/demonologist.jfif',
                image: 'icons/classes/demonologist.jfif',
                color1: 'yellow', // Sacred
                color2: 'purple', // Secondary 6 (Occultism)
                principalAttribute: 5,
                secondaryAttribute: 6,
                createdAt: now,
                updatedAt: now,
            },
            {
                id: 22,
                name: 'Occultist',
                description: 'Um praticante de artes ocultas que manipula segredos e energias proibidas.',
                icon: 'icons/classes/occultist.jfif',
                image: 'icons/classes/occultist.jfif',
                color1: 'purple', // Occultism
                color2: 'purple', // Secondary 6 (Occultism)
                principalAttribute: 6,
                secondaryAttribute: 6,
                createdAt: now,
                updatedAt: now,
            },
        ], {});
    },

    async down(queryInterface, Sequelize) {
        await queryInterface.bulkDelete('Classes', {
            id: { [Sequelize.Op.in]: [20, 21, 22] }
        }, {});
    }
};