'use strict';

module.exports = {
    async up(queryInterface, Sequelize) {
        const now = new Date();

        await queryInterface.bulkInsert('Jobs', [

            {
                name: 'Travelling',
                description: 'Travelling.',
                icon: 'jobs/travelling.jfif',
                difficulty: 0,
                attributeId: 2,
                experience: 0,
                gold: 0,
                createdAt: now,
                updatedAt: now,
            },
            // ===== Strength =====
            {
                name: 'Load and Carry Supplies',
                description: 'Manual labor focused on transporting heavy supplies across short distances.',
                icon: 'jobs/loadandcarrysupplies.jfif',
                difficulty: 10,
                attributeId: 1,
                experience: 10,
                gold: 20,
                createdAt: now,
                updatedAt: now,
            },
            {
                name: 'Arena Sparring Fighter',
                description: 'Participate in controlled combat to train warriors and entertain crowds.',
                icon: 'jobs/arenasparringfighter.jfif',
                difficulty: 12,
                attributeId: 1,
                experience: 15,
                gold: 35,
                createdAt: now,
                updatedAt: now,
            },
            {
                name: 'Heavy Construction Worker',
                description: 'Build fortifications and structures requiring raw physical endurance.',
                icon: 'jobs/heavyconstructionworker.jfif',
                difficulty: 14,
                attributeId: 1,
                experience: 25,
                gold: 55,
                createdAt: now,
                updatedAt: now,
            },
            {
                name: 'Frontline Shock Trooper',
                description: 'Serve as the first wave in brutal frontline assaults.',
                icon: 'jobs/frontlineshocktrooper.jfif',
                difficulty: 16,
                attributeId: 1,
                experience: 40,
                gold: 80,
                createdAt: now,
                updatedAt: now,
            },

            // ===== Intelligence =====
            {
                name: 'Translate Old Documents',
                description: 'Decipher and translate ancient texts and forgotten manuscripts.',
                icon: 'jobs/translateolddocuments.jfif',
                difficulty: 10,
                attributeId: 2,
                experience: 10,
                gold: 25,
                createdAt: now,
                updatedAt: now,
            },
            {
                name: 'Craft Simple Tools',
                description: 'Design and assemble basic tools using logic and technical knowledge.',
                icon: 'jobs/craftsimpletools.jfif',
                difficulty: 12,
                attributeId: 2,
                experience: 15,
                gold: 40,
                createdAt: now,
                updatedAt: now,
            },
            {
                name: 'Military Strategist Assistant',
                description: 'Assist in planning troop movements and battlefield logistics.',
                icon: 'jobs/militarystrategistassistant.jfif',
                difficulty: 14,
                attributeId: 2,
                experience: 30,
                gold: 65,
                createdAt: now,
                updatedAt: now,
            },
            {
                name: 'Master Engineer',
                description: 'Oversee complex engineering projects and advanced constructions.',
                icon: 'jobs/masterengineer.jfif',
                difficulty: 16,
                attributeId: 2,
                experience: 50,
                gold: 100,
                createdAt: now,
                updatedAt: now,
            },

            // ===== Dexterity =====
            {
                name: 'Silent Courier',
                description: 'Deliver sensitive messages without being seen or heard.',
                icon: 'jobs/silentcourier.jfif',
                difficulty: 10,
                attributeId: 3,
                experience: 10,
                gold: 30,
                createdAt: now,
                updatedAt: now,
            },
            {
                name: 'City Pickpocket',
                description: 'Steal valuables from unsuspecting citizens in crowded areas.',
                icon: 'jobs/citypickpocket.jfif',
                difficulty: 12,
                attributeId: 3,
                experience: 20,
                gold: 45,
                createdAt: now,
                updatedAt: now,
            },
            {
                name: 'Precision Archer',
                description: 'Provide ranged support with deadly accuracy.',
                icon: 'jobs/precisionarcher.jfif',
                difficulty: 14,
                attributeId: 3,
                experience: 35,
                gold: 70,
                createdAt: now,
                updatedAt: now,
            },
            {
                name: 'Elite Infiltrator',
                description: 'Penetrate secured locations without leaving a trace.',
                icon: 'jobs/eliteinfiltrator.jfif',
                difficulty: 16,
                attributeId: 3,
                experience: 55,
                gold: 110,
                createdAt: now,
                updatedAt: now,
            },

            // ===== Charisma =====
            {
                name: 'Market Negotiator',
                description: 'Handle commercial negotiations and trade agreements.',
                icon: 'jobs/marketnegotiator.jfif',
                difficulty: 10,
                attributeId: 4,
                experience: 10,
                gold: 35,
                createdAt: now,
                updatedAt: now,
            },
            {
                name: 'Tavern Performer',
                description: 'Entertain patrons through music, stories, and performance.',
                icon: 'jobs/tavernperformer.jfif',
                difficulty: 12,
                attributeId: 4,
                experience: 20,
                gold: 50,
                createdAt: now,
                updatedAt: now,
            },
            {
                name: 'Crime Syndicate Enforcer',
                description: 'Enforce the will of criminal organizations through fear and authority.',
                icon: 'jobs/crimesyndicateenforcer.jfif',
                difficulty: 14,
                attributeId: 4,
                experience: 40,
                gold: 85,
                createdAt: now,
                updatedAt: now,
            },
            {
                name: 'Political Figurehead',
                description: 'Serve as the public face of powerful political factions.',
                icon: 'jobs/politicalfigurehead.jfif',
                difficulty: 16,
                attributeId: 4,
                experience: 60,
                gold: 120,
                createdAt: now,
                updatedAt: now,
            },

            // ===== Sacred =====
            {
                name: 'Temple Acolyte',
                description: 'Assist priests and maintain sacred grounds.',
                icon: 'jobs/templeacolyte.jfif',
                difficulty: 10,
                attributeId: 5,
                experience: 10,
                gold: 20,
                createdAt: now,
                updatedAt: now,
            },
            {
                name: 'Ritual Healer',
                description: 'Perform healing rituals to restore body and spirit.',
                icon: 'jobs/ritualhealer.jfif',
                difficulty: 12,
                attributeId: 5,
                experience: 25,
                gold: 45,
                createdAt: now,
                updatedAt: now,
            },
            {
                name: 'Inquisitorial Judge',
                description: 'Judge heretics and enforce divine law.',
                icon: 'jobs/inquisitorialjudge.jfif',
                difficulty: 14,
                attributeId: 5,
                experience: 45,
                gold: 90,
                createdAt: now,
                updatedAt: now,
            },
            {
                name: 'High Priest',
                description: 'Lead religious orders and conduct major sacred ceremonies.',
                icon: 'jobs/highpriest.jfif',
                difficulty: 16,
                attributeId: 5,
                experience: 70,
                gold: 140,
                createdAt: now,
                updatedAt: now,
            },

            // ===== Occultism =====
            {
                name: 'Occult Assistant',
                description: 'Support forbidden rituals and dark research.',
                icon: 'jobs/occultassistant.jfif',
                difficulty: 10,
                attributeId: 6,
                experience: 15,
                gold: 30,
                createdAt: now,
                updatedAt: now,
            },
            {
                name: 'Curse Scribe',
                description: 'Inscribe curses and dark symbols for occult purposes.',
                icon: 'jobs/cursescribe.jfif',
                difficulty: 12,
                attributeId: 6,
                experience: 25,
                gold: 55,
                createdAt: now,
                updatedAt: now,
            },
            {
                name: 'Necromantic Researcher',
                description: 'Study death, undeath, and necromantic forces.',
                icon: 'jobs/necromanticresearcher.jfif',
                difficulty: 14,
                attributeId: 6,
                experience: 45,
                gold: 95,
                createdAt: now,
                updatedAt: now,
            },
            {
                name: 'Master Occultist',
                description: 'Command powerful dark arts and forbidden knowledge.',
                icon: 'jobs/masteroccultist.jfif',
                difficulty: 16,
                attributeId: 6,
                experience: 80,
                gold: 160,
                createdAt: now,
                updatedAt: now,
            },

            // ===== Mixed =====
            {
                name: 'Work at the Circus',
                description: 'Perform dangerous and deceptive acts for public entertainment.',
                icon: 'jobs/workatthecircus.jfif',
                difficulty: 18,
                attributeId: 1,
                experience: 90,
                gold: 180,
                createdAt: now,
                updatedAt: now,
            },
            {
                name: 'Bounty Hunter',
                description: 'Track, capture, or eliminate high-value targets.',
                icon: 'jobs/bountyhunter.jfif',
                difficulty: 18,
                attributeId: 1,
                experience: 100,
                gold: 200,
                createdAt: now,
                updatedAt: now,
            },
            {
                name: 'Cult Leader',
                description: 'Lead a cult through manipulation, faith, and dark influence.',
                icon: 'jobs/cultleader.jfif',
                difficulty: 18,
                attributeId: 1,
                experience: 120,
                gold: 240,
                createdAt: now,
                updatedAt: now,
            },
            {
                name: 'Relic Expedition Commander',
                description: 'Command expeditions seeking ancient and dangerous relics.',
                icon: 'jobs/relicexpeditioncommander.jfif',
                difficulty: 18,
                attributeId: 1,
                experience: 130,
                gold: 260,
                createdAt: now,
                updatedAt: now,
            },

        ], {});
    },

    async down(queryInterface, Sequelize) {
        await queryInterface.bulkDelete('Jobs', null, {});
    }
};